# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fd46ccfee09e24a79f542050b25e8d09d4d0d1ce7fd00a367c75c65686aea430b11245c903c61142d8c7d7f6f566b72f73a73c138319caa2ed363c09bcafdb2

test:
  secret_key_base: c12c000f1e1d9c061e4bb142904638d45a6a25766c689d4a80cebef06df01afb6676d471e653abbc4cab073a7673c5844fe80f2e03a45e0456af55fd7b5cfe03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
